package render

import (
	"fmt"
	"strings"
)

// IncludeDir is the subdirectory, relative to bird.conf, that birdy writes its
// per-section files into. birdy owns this directory exclusively: every apply
// rewrites the files the model needs and removes any it no longer does.
const IncludeDir = "birdy.d"

// File is one file birdy writes under the config directory. Name is a POSIX
// path relative to that directory, e.g. "birdy.d/09-peers-edge1.conf".
type File struct {
	Name string `json:"name"`
	Body string `json:"body"`
}

// FileSet is the rendered config laid out across several files: the entry
// bird.conf (a short banner plus a list of includes) and one include file per
// section. Concatenating Includes[i].Body in order reproduces Config(in)
// byte-for-byte, so the logical config birdy hashes and diffs is independent of
// how it is split on disk. Entry itself is layout metadata (its bytes carry the
// absolute include paths) and is deliberately not part of that logical config.
type FileSet struct {
	Entry    string `json:"entry"`
	Includes []File `json:"includes"`
}

// Logical returns the concatenation of the include bodies — what BIRD parses
// once the includes are spliced in, and equal to Config(in).
func (fs FileSet) Logical() string {
	var b strings.Builder
	for _, f := range fs.Includes {
		b.WriteString(f.Body)
	}
	return b.String()
}

// groupNum numbers the top-level section groups so an operator listing birdy.d/
// sees related files together (all peers, all sets). The number is stable per
// group, so adding a peer or a set never renumbers unrelated files. The actual
// load order is set by the ordered include lines in bird.conf, not by these
// names, so grouping does not have to match load order exactly.
var groupNum = map[string]string{
	"header":      "00",
	"globals":     "01",
	"communities": "02",
	"sets":        "03",
	"bogons":      "04",
	"rpki":        "05",
	"protocols":   "06",
	"static":      "07",
	"policies":    "08",
	"peers":       "09",
	"raw":         "10",
}

// includeFileName maps a section path to its file under IncludeDir, e.g.
// "peers/edge1" -> "birdy.d/09-peers-edge1.conf".
func includeFileName(sectionPath string) string {
	group := sectionPath
	if i := strings.IndexByte(sectionPath, '/'); i >= 0 {
		group = sectionPath[:i]
	}
	num, ok := groupNum[group]
	if !ok {
		num = "99"
	}
	slug := strings.ReplaceAll(sectionPath, "/", "-")
	return IncludeDir + "/" + num + "-" + slug + ".conf"
}

// Files lays the rendered config out as a bird.conf that includes one file per
// section under IncludeDir. dir is the absolute directory bird.conf lives in,
// used to build absolute include paths — absolute so BIRD resolves them the same
// no matter what its working directory or relative-include rules are. The result
// is a pure function of (in, dir).
func Files(in Input, dir string) (FileSet, error) {
	secs, err := Sections(in)
	if err != nil {
		return FileSet{}, err
	}
	base := strings.TrimRight(strings.ReplaceAll(dir, "\\", "/"), "/")
	if base == "" {
		base = "."
	}

	var entry strings.Builder
	writeEntryHeader(&entry, in.Version)
	includes := make([]File, 0, len(secs))
	for _, s := range secs {
		name := includeFileName(s.Path)
		fmt.Fprintf(&entry, "include \"%s/%s\";\n", base, name)
		includes = append(includes, File{Name: name, Body: s.Body})
	}
	return FileSet{Entry: entry.String(), Includes: includes}, nil
}

func writeEntryHeader(b *strings.Builder, version string) {
	fmt.Fprintf(b, `#
# bird.conf generated by birdy %s
#
# birdy owns this file and the %s/ directory beside it, and rewrites them in
# full from its database on every apply. This file only pulls in the generated
# sections below; change the model in the birdy UI, not the files — hand edits
# are lost on the next apply.
#

`, version, IncludeDir)
}
