package render

import (
	"strings"
	"testing"

	"github.com/floreabogdan/birdy/internal/store"
)

func richInput() Input {
	in := baseInput()
	in.PrefixSets = bogonSets()
	in.Policies = []store.Policy{sanityPolicy()}
	p := ebgpPeer()
	p.ImportPolicies = []store.Policy{sanityPolicy()}
	in.Peers = []store.Peer{p}
	in.BMPStations = []store.BMPStation{{Name: "collector", Address: "198.51.100.10", Port: 1790, Enabled: true, PrePolicy: true}}
	return in
}

// The whole invariant: the include bodies concatenated must reproduce Config
// byte-for-byte, so the apply pipeline's hash and diff are unaffected by the
// on-disk split.
func TestFilesLogicalEqualsConfig(t *testing.T) {
	in := richInput()
	cfg := mustRender(t, in)
	fs, err := Files(in, "/etc/bird")
	if err != nil {
		t.Fatalf("Files: %v", err)
	}
	if got := fs.Logical(); got != cfg {
		t.Fatalf("Logical() must equal Config output byte-for-byte\n--- want ---\n%s\n--- got ---\n%s", cfg, got)
	}
}

// bird.conf is a banner plus one absolute include line per section, in order.
func TestFilesEntryHasOrderedAbsoluteIncludes(t *testing.T) {
	in := richInput()
	fs, err := Files(in, "/etc/bird")
	if err != nil {
		t.Fatalf("Files: %v", err)
	}
	// One include line per include file, in the same order.
	var lines []string
	for _, ln := range strings.Split(fs.Entry, "\n") {
		if strings.HasPrefix(ln, "include ") {
			lines = append(lines, ln)
		}
	}
	if len(lines) != len(fs.Includes) {
		t.Fatalf("got %d include lines for %d files", len(lines), len(fs.Includes))
	}
	for i, f := range fs.Includes {
		want := `include "/etc/bird/` + f.Name + `";`
		if lines[i] != want {
			t.Errorf("include %d = %q, want %q", i, lines[i], want)
		}
		if !strings.HasPrefix(f.Name, IncludeDir+"/") || !strings.HasSuffix(f.Name, ".conf") {
			t.Errorf("include file %q is not under %s/ with a .conf suffix", f.Name, IncludeDir)
		}
	}

	// Recognisable per-section names.
	names := map[string]bool{}
	for _, f := range fs.Includes {
		names[f.Name] = true
	}
	for _, want := range []string{
		"birdy.d/00-header.conf",
		"birdy.d/09-peers-edge_v4.conf",
		"birdy.d/08-policies-IMPORT_SANITY.conf",
		"birdy.d/06-protocols-bmp.conf",
	} {
		if !names[want] {
			t.Errorf("missing include file %q (have %v)", want, names)
		}
	}
}

// A different config directory only changes the absolute include paths, never
// the include bodies (the logical config).
func TestFilesDirOnlyAffectsEntry(t *testing.T) {
	in := richInput()
	a, _ := Files(in, "/etc/bird")
	b, _ := Files(in, "/opt/bird/conf")
	if a.Logical() != b.Logical() {
		t.Error("the config directory must not change the logical config")
	}
	if a.Entry == b.Entry {
		t.Error("the entry file should carry the directory-specific include paths")
	}
	if !strings.Contains(b.Entry, `include "/opt/bird/conf/birdy.d/00-header.conf";`) {
		t.Errorf("entry did not use the given directory:\n%s", b.Entry)
	}
}

// An empty-ish model still produces a valid split: bird.conf plus at least the
// header and base protocol sections.
func TestFilesMinimalModel(t *testing.T) {
	fs, err := Files(baseInput(), "/etc/bird")
	if err != nil {
		t.Fatalf("Files: %v", err)
	}
	if len(fs.Includes) == 0 {
		t.Fatal("expected at least one include file")
	}
	if !strings.Contains(fs.Entry, "generated by birdy") {
		t.Error("entry banner missing")
	}
}
